name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: python
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run ruff
        run: uv run ruff check
      - name: Run tests
        run: uv run src/wlgen/tests/__init__.py
      - name: Build
        run: uv build
      - name: Publish package distributions to PyPI
        if: ${{ github.event_name == 'push' }}
        uses: pypa/gh-action-pypi-publish@release/v1
