name: publish to pypi

on:
  workflow_run:
    workflows: ["build pipeline"]
    types: [completed]
    branches: [main]

jobs:
  publish_to_pypi:
    name: publish to pypi
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: download build artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: build
          path: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        if: ${{ success() }}
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        if: ${{ success() }}
        with:
          python-version-file: "pyproject.toml"

      - name: publish to pypi
        if: ${{ success() }}
        run: uv publish
